### ISSUE TITLE
Node Properties vs Node Features?

### ISSUE THREAD

**Issue by perara** [cair/GraphTsetlinMachine#66]
I might have misunderstood this fully, but is there a reason for the convention "Node Properties" and not "Node Features" or "Node Mode/modality"?

In the case where "node Properties" is needed as a new term, what is the difference between the features of the data input to the node, and Node Properties? 

![Screenshot_20241105_231708_Chrome](https://github.com/user-attachments/assets/263bd96c-d992-4f69-b69d-e4d0e757af67)

**Comment by olegranmo** [comment]
The reason is the vector symbolic approach. The properties are symbols, which in turn, are mapped to features in a feature vector internally.
